order_expired:
  cron: "1 3 * * *"
  class: "OrderExpired"
  queue: default

order_day_arrived:
  cron: "10 3 * * *"
  class: "OrderDayArrivedJob"
  queue: default

professional_arrived_at_service:
  cron: "*/15 * * * *"
  class: "ProfessionalArrivedAtServiceAddressJob"
  queue: default
  
one_day_earlier_then_order_day:
  cron: "20 3 * * *"
  class: "OneDayEarlierThenOrderDayJob"
  queue: default
