order_expired:
  cron: "0 3 * * *"
  class: "OrderExpired"
  queue: default

#second_job:
#  cron: "*/30 * * * *" # execute at every 30 minutes
#  class: "HardWorker"
#  queue: hard_worker_long
#  args:
#    hard: "stuff"
