:schedule:
  testa_scheduler:
    every: '10s' # Roda a cada 10 segundos
    class: TesteJob
    # Pode ser por intervalo de tempo
    
    
  testa_scheduler_2:
    cron: '0 * * * * *' # Roda uma vez por minuto no segundo 0
    class: TestePorCronJob
    # Por cron
